### ISSUE TITLE
Cargo Error: "error[E0635]: unknown feature `proc_macro_span_shrink`" when building.

### ISSUE THREAD

**Issue by sophiel-meow** [google/OpenSK#549]
## Actual Behavior
　　When running deploy script(develop branch) to build openSK or erase_storage for nrf52840_dongle with "./deploy.py --board=nrf52840_dongle_dfu --erase_storage --programmer=nordicdfu", it goes wrong showing "error[E0635]: unknown feature 'proc_macro_span_shrink'". More info shows below:
<br />

`info: Building example erase_storage`
`   Compiling proc-macro2 v1.0.44`
`   Compiling num-iter v0.1.43`
`   Compiling num-rational v0.3.2`
`error[E0635]: unknown feature 'proc_macro_span_shrink'`
`  --> /home/herrscherzero/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.44/src/lib.rs:92:30`
`   |`
`92 |     feature(proc_macro_span, proc_macro_span_shrink)`
`   |                              ^^^^^^^^^^^^^^^^^^^^^^`
``
`error: aborting due to previous error`
``
`For more information about this error, try 'rustc --explain E0635'.`
`error: could not compile 'proc-macro2'`
``
`To learn more, run the command again with --verbose.`
`warning: build failed, waiting for other jobs to finish...`
`error: build failed`
`fatal: Failed to execute cargo: Command '['cargo', 'build', '--release', '--target=thumbv7em-none-eabi', '--features=with_ctap1', '--example', 'erase_storage']' returned non-zero exit status 101.`
``
## Specifications

- Version: f2fac83
- Platform: Arch Linux (x86_64)

**Comment by kaczmarczyck** [comment]
Initial assessment: I can reproduce after a `cargo update`. It did a suspicious version jump there:
`proc-macro2 v1.0.43 -> v1.0.44`
So before we have it fixed, I suspect you can lock the crate's version.

**Comment by sophiel-meow** [comment]
> Initial assessment: I can reproduce after a `cargo update`. It did a suspicious version jump there: `proc-macro2 v1.0.43 -> v1.0.44` So before we have it fixed, I suspect you can lock the crate's version.

Thanks for replying.
I noticed that the new released [commit for proc-macro2](https://github.com/dtolnay/proc-macro2/commit/cc97264f9f324ade9b820a1629f379b2cbb6e632) showes that a new feature "proc_macro_span_shrink" was added to src/lib.rc. After removing such feature, the compilation would be succeed.
But it is shamed to say hat I haven't got alone with Rust well, Any suggestion with that? Looking forward to your early reply.

Thanks and Regards,
Jun.

**Comment by kaczmarczyck** [comment]
Hi! You are correct, that is what's going on. We can simply pin the version to 1.0.43, and we should be good.

Thanks for reporting, and feel free to report back if #550 fixes your problem once it is merged!

**Comment by sophiel-meow** [comment]
The issued has been fixed.
Closed.

**Comment by JohnVersus** [comment]
Hi, I have the same error on Mac M1 and tried adding `proc-macro2 = "=1.0.43"` in dependencies. But it did not work. 

In return it gave me a bunch of errors that look like these. Am I missing something or Is there any other fix?
```bash
error[E0433]: failed to resolve: could not find `Span` in `proc_macro`
  --> /Users/johnversus/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.43/src/detection.rs:67:49
   |
67 |     let works = panic::catch_unwind(proc_macro::Span::call_site).is_ok();
   |                                                 ^^^^ could not find `Span` in `proc_macro`

error[E0433]: failed to resolve: could not find `Spacing` in `proc_macro`
   --> /Users/johnversus/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.43/src/wrapper.rs:158:47
    |
158 |                 Spacing::Joint => proc_macro::Spacing::Joint,
    |                                               ^^^^^^^ could not find `Spacing` in `proc_macro`

error[E0433]: failed to resolve: could not find `Spacing` in `proc_macro`
   --> /Users/johnversus/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.43/src/wrapper.rs:159:47
    |
159 |                 Spacing::Alone => proc_macro::Spacing::Alone,
    |                                               ^^^^^^^ could not find `Spacing` in `proc_macro`

error[E0433]: failed to resolve: could not find `token_stream` in `proc_macro`
   --> /Users/johnversus/.cargo/registry/src/github.com-1ecc6299db9ec823/proc-macro2-1.0.43/src/wrapper.rs:303:26
    |
303 |     Compiler(proc_macro::token_stream::IntoIter),
    |                          ^^^^^^^^^^^^ could not find `token_stream` in `proc_macro`

```

**Comment by kaczmarczyck** [comment]
We did not backport the fix to stable yet. Can you confirm that you are on the stable branch? In that case, I'll respond on #553 since it seems to be same problem.

**Comment by JohnVersus** [comment]
Yes, I am on stable and I tested on the `nightly` and `span-locations` features with the same version, and it still throws an error.

**Comment by kaczmarczyck** [comment]
Please let me know if your problem is solved on stable now!

**Comment by JohnVersus** [comment]
Hey @kaczmarczyck, yup it is solved now. Thanks 🤩
